create or replace PACKAGE HASH AS 

    --SUBTYPE SHA1_CHECKSUM_VARCHAR2 IS VARCHAR2(20);
    --SUBTYPE SHA1_CHECKSUM_RAW IS RAW(20);
    SUBTYPE SHA256_CHECKSUM_RAW IS RAW(32);
    SUBTYPE SHA256_CHECKSUM_HEX IS VARCHAR2(64);

    /* Final Function */
    --FUNCTION SHA1(X IN RAW) RETURN RAW;
    FUNCTION SHA256(X IN RAW) RETURN SHA256_CHECKSUM_RAW;
    FUNCTION SHA256(X IN VARCHAR2) RETURN SHA256_CHECKSUM_RAW;
    FUNCTION SHA256HEX(X IN RAW) RETURN SHA256_CHECKSUM_HEX;
    FUNCTION SHA256HEX(X IN VARCHAR2) RETURN SHA256_CHECKSUM_HEX;

END HASH;