create or replace PACKAGE HASH AS 

    SUBTYPE SHA1_CHECKSUM_RAW IS RAW(20);
    SUBTYPE SHA256_CHECKSUM_RAW IS RAW(32);

    FUNCTION SHA1(X IN RAW) RETURN SHA1_CHECKSUM_RAW;
    FUNCTION SHA256(X IN RAW) RETURN SHA256_CHECKSUM_RAW;

END HASH;